### ISSUE TITLE
Communiceren naar andere groep i.v.m. communicationprotocol

### ISSUE THREAD

**Issue by Koffiejoe** [randomRexx/ADAS_AI_cart#25]
[
![bewijssamenkomengroep](https://user-images.githubusercontent.com/50230637/77918169-ccd17d80-729b-11ea-8bbd-8e8442040d7f.png)
](url)

JSON formaat via UART: afstand en hoek tov obstakel, afstand tov lijnen

**Comment by cteqeu** [comment]
Voorbeeld json format (met dummy data), ga je ook via UDP ?
