### ISSUE TITLE
Camera programma integreren op Ultra96

### ISSUE THREAD

**Issue by Nightwolve** [randomRexx/ADAS_AI_cart#43]

**Comment by i5cP7i** [comment]
Na aansluiten van de voeding, mini display naar displayport en na booten Ultra96 geen output naar het scherm.

**Comment by i5cP7i** [comment]
Nieuwe SD kaart geflashed  een en succesvolle boot + output met miniDP <-> DP adapter. 
![ultra96conn](https://user-images.githubusercontent.com/48355782/96506295-af73f900-1257-11eb-9426-b8ac6daaed40.jpg)


![ultra96home](https://user-images.githubusercontent.com/48355782/96506277-a7b45480-1257-11eb-9654-91bb77a7677a.jpg)
