### ISSUE TITLE
python programma op ultra96 zetten al dan niet via USB

### ISSUE THREAD

**Issue by Nightwolve** [randomRexx/ADAS_AI_cart#72]

**Comment by i5cP7i** [comment]
USB: exFAT is not supported. (file size > 2 GB). 
Potential solution: 
Install packages exfat-fuse exfat-utils => WiFi / internet connection required.

 WiFi setup failed: could not establish internet connection. Methods: Hotspot / WAP

**Comment by i5cP7i** [comment]
fixed issue resolution: xrandr -s 1920x1080

**Comment by i5cP7i** [comment]
- no dhclient command found
- udhcpc no such device

Cannot associate with network: iwconfig wlan0 returns Access point: Not-Associated

Cannot establish internet connection, cannot get an IP address using DHCP, cannot get static IP using a mask.

**Comment by i5cP7i** [comment]
cannot automate wlan setup using: auto wlan0 => auto command not found.

**Comment by i5cP7i** [comment]
Conclusion:
wlan0 is up, but no internet connection

**Comment by i5cP7i** [comment]
info: setup inet
iwlist wlan0 scan | grep SSID
wpa_passphrase "ssid" "passw" >> /etc/wpa_supplicant.conf
wpa_supplicant -i wlan0 -Dwext -c /etc/wpa_supplicant.conf
